services:
    oai-gnb:
        image: oai-gnb-fhi72:latest
        privileged: true
        container_name: oai-gnb
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --sa --thread-pool 13,14,15,16,17,18
        devices:
            - /dev/vfio:/dev/vfio/
        volumes:
            - ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb.sa.band78.273prb.fhi72.4x4-benetel650.conf:/opt/oai-gnb/etc/gnb.conf
            - /dev/hugepages:/dev/hugepages
        cpuset: "0,1,2,8,9,10,13,14,15,16,17,18"
        networks:
            oai-net:
                ipv4_address: 172.21.18.20
        healthcheck:
           test: /bin/bash -c "pgrep nr-softmodem"
           interval: 10s
           timeout: 5s
           retries: 5
networks:
    oai-net:
        driver: macvlan
        name: oai-net
        ipam:
            config:
                - subnet: "172.21.16.0/22"
                  ip_range: "172.21.18.20/32"
                  gateway: "172.21.19.254"
        driver_opts:
            com.docker.network.bridge.name: "oai-net"
            parent: enp193s0f0
