services:
    oai-nr-ue:
        image: oai-nr-ue:latest
        network_mode: host
        container_name: oai-nr-ue
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
            - SYS_NICE   # for performance
            - IPC_LOCK   # for memory locking
        devices:
             - /dev/net/tun:/dev/net/tun
        ulimits:
          core: -1 # for core dumps
        #entrypoint: /bin/bash -c "sleep infinity"
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --usrp-args type=n3xx,name=ni-n3xx-31641B9,addr=192.168.10.2 -r 106 --numerology 1 --band 78 -C 3511200000 --sa --ue-fo-compensation --ue-rxgain 65 --tune-offset 20000000 -A 90 --log_config.global_log_options level,nocolor,time --uicc0.imsi 001020000000111 --uicc0.nssai_sd 16777215
        volumes:
            - ../../conf_files/ue.sa.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
